### PR TITLE
Add Welcome in zh-Hant

### PR DESCRIPTION
**Pull request by WinstonSung**
Add Welcome in Mandarin (Traditional Han script) (Traditional Chinese)

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Thanks @WinstonSung

**Comment by WinstonSung** [comment]
(Change approved but haven't merge.)

**Comment by WinstonSung** [comment]
CC @bsmth

**Comment by bsmth** [comment]
Hi @WinstonSung, merging now 👍🏻

**Pull request merged**
